name: libwasmer-release

on:
  release:
    types:
      - created


env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build dynamic library for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-18.04
            artifact_name: libwasmer_linux_amd64.so
            make_target: capi-linux-amd64
          - os: macos-11
            artifact_name: libwasmer_darwin_amd64.dylib
            make_target: capi-osx-amd64
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Make
        run: make capi-linux-amd64
      - name: Get the version
        id: get_version
        if: startsWith(github.ref, 'refs/tags/')
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: ${{ steps.get_version.outputs.VERSION }}-linux-amd64
          files: |
            target/release/${{ matrix.artifact_name }}
